# Generated by Django 4.0 on 2022-01-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicapp', '0002_rename_comics_comic'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='image',
            field=models.ImageField(default='test', upload_to='images'),
            preserve_default=False,
        ),
    ]
