# Generated by Django 4.0 on 2022-01-13 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comicapp', '0003_comic_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(default='SERIES', max_length=200)),
                ('publishing', models.CharField(max_length=300)),
                ('episodes', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comicapp.comicseries'),
            preserve_default=False,
        ),
    ]
