# Generated by Django 4.0 on 2022-01-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicapp', '0004_comicseries_comic_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='subscriber',
            field=models.ManyToManyField(blank=True, null=True, to='comicapp.Available'),
        ),
    ]
