# Generated by Django 4.0 on 2022-01-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicapp', '0006_rename_subscriber_comic_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='date',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
